version: "3.9"

services:
  place_publique:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: place_publique
    environment:
      - PORT=5000
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs
      - ./mlruns:/app/mlruns
    shm_size: "1gb"
    restart: unless-stopped
